name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]   # deploys whenever you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Build & Push image
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$REPO_NAME

      - name: Deploy to Cloud Run
        run: gcloud run deploy $REPO_NAME \
              --image gcr.io/$PROJECT_ID/$REPO_NAME \
              --region us-central1 \
              --vpc-connector YOUR_VPC_CONNECTOR \
              --allow-unauthenticated
